echo "compare-record-and-nil.tig"
./tiger tests/good/compare-record-and-nil.tig
echo "fact.tig"
./tiger tests/good/fact.tig
echo "local-vs-global-type.tig"
./tiger tests/good/local-vs-global-type.tig
echo "merge.tig"
./tiger tests/good/merge.tig
echo "queens.tig"
./tiger tests/good/queens.tig
echo "recursive-comments.tig"
./tiger tests/good/recursive-comments.tig
echo "recursive-types.tig"
./tiger tests/good/recursive-types.tig
echo "test01.tig"
./tiger tests/good/test01.tig
echo "test02.tig"
./tiger tests/good/test02.tig
echo "test03.tig"
./tiger tests/good/test03.tig
echo "test06.tig"
./tiger tests/good/test06.tig
echo "test07.tig"
./tiger tests/good/test07.tig
echo "test08.tig"
./tiger tests/good/test08.tig
echo "test12.tig"
./tiger tests/good/test12.tig
echo "test27.tig"
./tiger tests/good/test27.tig
echo "test30.tig"
./tiger tests/good/test30.tig
echo "test37.tig"
./tiger tests/good/test37.tig
echo "test42.tig"
./tiger tests/good/test42.tig
echo "test44.tig"
./tiger tests/good/test44.tig
echo "test47.tig"
./tiger tests/good/test47.tig
echo "test48.tig"
./tiger tests/good/test48.tig
echo "test50.tig"
./tiger tests/good/test50.tig
echo "three-name-spaces.tig"
./tiger tests/good/three-name-spaces.tig
