./tiger tests/good/compare-record-and-nil.tig
./tiger tests/good/fact.tig
./tiger tests/good/local-vs-global-type.tig
./tiger tests/good/merge.tig
./tiger tests/good/queens.tig
./tiger tests/good/recursive-comments.tig
./tiger tests/good/recursive-types.tig
./tiger tests/good/test01.tig
./tiger tests/good/test02.tig
./tiger tests/good/test03.tig
./tiger tests/good/test06.tig
./tiger tests/good/test07.tig
./tiger tests/good/test08.tig
./tiger tests/good/test12.tig
./tiger tests/good/test27.tig
./tiger tests/good/test30.tig
./tiger tests/good/test37.tig
./tiger tests/good/test42.tig
./tiger tests/good/test44.tig
./tiger tests/good/test47.tig
./tiger tests/good/test48.tig
./tiger tests/good/test50.tig
./tiger tests/good/three-name-spaces.tig
